###########################################
# WarpStream - MinIO
###########################################
services:
  # Minio Storage Server
  storage:
    image: minio/minio
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9090:9090
    volumes:
      - ./data:/data
    command: ["server", "/data", "--console-address", ":9090"]
  # Minio Client Container
  mc:
    depends_on:
      - storage
    image: minio/mc
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://storage:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warpstream-minio-bucket;
      /usr/bin/mc mb minio/warpstream-minio-bucket;
      /usr/bin/mc policy set public minio/warpstream-minio-bucket;
      tail -f /dev/null
      "
  warp:
    image: public.ecr.aws/warpstream-labs/warpstream_agent:latest
    environment:
      - WARPSTREAM_DISCOVERY_KAFKA_HOSTNAME_OVERRIDE=localhost
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    command:
        - agent
        - -advertiseHostnameStrategy
        - custom
        - -advertiseHostnameCustom
        - localhost
        - -bucketURL 
        - s3://warpstream-minio-bucket?region=us-east-1&s3ForcePathStyle=true&endpoint=http://storage:9000
        - -defaultVirtualClusterID 
        - ${VIRTUAL_CLUSTER_ID}
        - -region 
        - us-east-1
        - -agentKey
        - ${AGENT_KEY}
    depends_on:
      - storage
    ports:
      - 9092:9092
    healthcheck:
      # Wait for the Agent to finish setting up the demo before marking it as healthy
      # to delay the diagnose-connection command from running for a few seconds.
      test: ["CMD", "sh", "-c", "sleep 10"]
      interval: 5s
      timeout: 15s
      retries: 5
